"""Initial model

Revision ID: 0cf78d176fc3
Revises: 
Create Date: 2019-09-21 16:07:33.669611+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf78d176fc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('password', sa.Binary(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('registered', sa.DateTime(), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.Column('logotype', sa.Text(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('about_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_time', sa.Integer(), nullable=False),
    sa.UniqueConstraint('user_id', 'title', name='post_user_id_title_key'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id'),
    )
    op.create_table('service_subscribe',
    sa.Column('service_subscribe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=32), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_subscribe_id')
    )
    op.create_table('post_tag',
    sa.Column('post_tag_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(256), nullable=False, index=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tag')
    op.drop_table('service_subscribe')
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
